# Use the official Bun Alpine-based image
FROM oven/bun:1.2.9-alpine

# Install git
RUN apk add --no-cache git

# Set working directory (optional, because you also define it in docker-compose)
WORKDIR /app
