version: '3.9'
name: ichablog-be

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP server port
      - "8025:8025"   # Web UI

  redis:
    image: redis:7-alpine
    container_name: ichablog_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ../data/redis_data:/data

  resque-web:
    image: appwrite/resque-web:1.1.0
    ports:
      - "5678:5678"
    environment:
      - RESQUE_WEB_HOST=redis
      - RESQUE_WEB_PORT=6379
      - RESQUE_WEB_HTTP_BASIC_AUTH_USER=ichablog
      - RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD=ichablog

  mariadb:
    image: mariadb:11.7
    container_name: ichablog_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ichablog
      MYSQL_USER: ichablog
      MYSQL_PASSWORD: ichablog
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ../data/mariadb_data:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: ichablog_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ichablog
      MINIO_ROOT_PASSWORD: ichablog
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ../data/minio_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.14
    container_name: ichablog_meilisearch
    restart: unless-stopped
    ports:
      - "${MEILISEARCH_PORT:-7700}:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: "masterKey"
    volumes:
      - ../data/meili_data:/meili_data

  bun:
    build:
      context: .
      dockerfile: Dockerfile.bun-alpine-git
    image: ichablog-bun
    container_name: ichablog_bun
    working_dir: /app
    volumes:
      - bun_cache:/root/.bun
      - ../:/app
      - ~/.ssh:/root/.ssh:ro
      - ~/.ssh/config.docker:/root/.ssh/config:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    command: ["bun", "dev:http"]
    depends_on:
      - redis
      - mariadb
      - minio
      - meilisearch
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"

  workers:
    build:
      context: .
      dockerfile: Dockerfile.bun-alpine-git
    image: ichablog-bun
    container_name: ichablog_workers
    working_dir: /app
    volumes:
      - ../:/app
      - bun_cache:/root/.bun
    command: ["bun", "dev:workers"]
    depends_on:
      - redis
      - mariadb
      - minio
      - meilisearch
    env_file:
      - .env

volumes:
  bun_cache: